# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2

jobs:
  build:
     docker:

     steps:
       - checkout
       - run: npm install
       - run: npm test
